# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :"mod2-2" => {
    :box_name => "bento/centos-7.2",
    :ip_addr => "192.168.11.250",
    :memory => "128",
    :shell => "mod2-2.sh"
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider "virtualbox" do |vb|
            vb.name = boxname.to_s
            vb.memory = boxconfig[:memory]
          end

          box.vm.provision "shell", path: boxconfig[:shell]
      end
  end
end