---
- name: Copy configs for ELK & hosts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'elasticsearch.yml', dest: '/etc/elasticsearch/elasticsearch.yml', group: elasticsearch, mode: '0660' }
    - { src: 'filebeat.yml', dest: '/etc/filebeat/filebeat.yml', group: root, mode: '0600' }
    - { src: 'system.yml', dest: '/etc/filebeat/modules.d/system.yml', group: root, mode: '0644'  }
    - { src: 'kibana.yml', dest: '/etc/kibana/kibana.yml', group: root, mode: '0644'  }
    - { src: 'hosts', dest: '/etc/hosts', group: root, mode: '0644'  }
  notify:
    - Enable and start ELK services 
...