# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :"mod2-3" => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
          end

          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd

            yum install -y ansible

            cp -R /vagrant/ansible_mod2-3/ ~/ansible
            cd ~/ansible
            ansible-playbook -i inventory.yml mod2-3.yml

            echo "============================================"
            for ip in $(hostname -I); do echo "IP адрес для подключения - $ip"; done
            echo "============================================"

          SHELL
      end
  end
end