# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :"bkp-client" => {
    :box_name => "bento/centos-7.2",
    :ip_addr => "192.168.11.251",
    :memory => "128",
    :shell => "bkp-client.sh",
    :ansible => "backup-client.yml"
  },
  :"bkp-srv" => {
    :box_name => "bento/centos-7.2",
    :ip_addr => "192.168.11.250",
    :memory => "256",
    :shell => "bkp-srv.sh",
    :ansible => "backup-srv.yml"
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.provision "shell", path: "shell/" + boxconfig[:shell]
      box.vm.provider "virtualbox" do |vb|
        vb.name = boxname.to_s
        vb.memory = boxconfig[:memory]
      end
#      box.vm.provision "ansible_local" do |ansible|
#        ansible.playbook = "ansible/" + boxconfig[:ansible]
#	    end
      box.vm.provision "shell", path: "shell/test_task.sh"
    end
  end
end