---
- name: Copy configs for ELK & hosts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'elasticsearch.yml', dest: '/etc/elasticsearch/elasticsearch.yml', group: elasticsearch, mode: '0660' }
    - { src: 'input.conf', dest: '/etc/logstash/conf.d/input.conf', group: root, mode: '0644'  }
    - { src: 'filter.conf', dest: '/etc/logstash/conf.d/filter.conf', group: root, mode: '0644'  }
    - { src: 'output.conf', dest: '/etc/logstash/conf.d/output.conf', group: root, mode: '0644'  }
    - { src: 'filebeat.yml', dest: '/etc/filebeat/filebeat.yml', group: root, mode: '0600' }
    - { src: 'system.yml', dest: '/etc/filebeat/modules.d/system.yml', group: root, mode: '0644'  }
    - { src: 'kibana.yml', dest: '/etc/kibana/kibana.yml', group: root, mode: '0644'  }
    - { src: 'hosts', dest: '/etc/hosts', group: root, mode: '0644'  }
    - { src: 'elk-master.conf', dest: '/etc/rsyslog.d/elk-master.conf', group: root, mode: '0644'  }
    - { src: 'config.php', dest: '/var/www/html/loganalyzer/config.php', group: root, mode: '0755'  }
  notify:
    - Enable and start ELK & httpd services

...