# -*- mode: ruby -*-
# vim: set ft=ruby :

require 'yaml'
nodes = YAML.load_file('nodes.yml')

Vagrant.configure(2) do |config|
  nodes.each do |nodes|

    config.vm.define nodes["name"] do |node|
      node.vm.hostname = nodes["name"]
      node.vm.box = "centos/7"

      node.vm.provider "virtualbox" do |vb|
        vb.name = nodes["name"]
        vb.memory = 256
        vb.cpus = 1
      end

      nodes["netInt"].each do |param|
        node.vm.network "private_network", param
      end

      if nodes.key?("extInt")
        nodes["extInt"].each do |param|
          node.vm.network "public_network", param
        end
      end

      node.vm.synced_folder "./sync", "/vagrant"

      node.vm.provision "shell", path: "shell/" + nodes["name"].to_s + ".sh"

    end
  end

end