---
- include_vars:
    file: ansible/roles/ipaclient/files/id_rsa.pub
    name: ssh-rsa

- ipa_user:
    name: wildway
    state: present
    sshpubkey:
    - ssh-rsa "{{ ssh-rsa }}"
    ipa_host: ipaserver.wildway.lan
    ipa_user: "{{ freeipa_server_admin_acc }}"
    ipa_pass: "{{ freeipa_server_admin_password }}"

...