#!/bin/sh

LOG_FILE="/var/log/pam_script.log"
ISDAYOFF=$(curl https://isdayoff.ru/`date '+%Y%m%d'` 2>/dev/null)

admin_access(){

    groups $PAM_USER | grep -Ew admin$ &>/dev/null

    if [[ $? == 0 ]] ; then
        echo "Доступ в систему пользователю $PAM_USER разрешён." >> $LOG_FILE
        return 0
    else
        echo "Доступ в систему пользователю $PAM_USER запрещён." >> $LOG_FILE
        return 1
    fi
}


echo "`date '+%F %T'` пользователь $PAM_USER успешно обработан с помощью pam_script" >> $LOG_FILE

if [[ $ISDAYOFF == 0 ]] ; then
    echo -e "Сегодня рабочий день.\nДоступ разрешён." >> $LOG_FILE
    exit 0
elif [[ $ISDAYOFF == 1 ]] ; then
    echo "Сегодня выходной/праздничный день. Проверка членства в группе администраторов" >> $LOG_FILE
    exit `admin_access` $?
else
    echo "Сервис обработки праздничных дней не доступен." >> $LOG_FILE
    if [[ `date '+%u'` -gt 5 ]] ; then
        echo "Сегодня выходной день. Проверка членства в группе администраторов." >> $LOG_FILE
        exit `admin_access` $?
    fi
fi