---
- name: Enable and start mariadb
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Copy rsyslog's sql query to tmp
  copy:
    src: rsyslog-mysql.sql
    dest: /tmp/rsyslog-mysql.sql

- name: Configure mysql for rsyslog
  mysql_db:
    state: import
    name: all
    target: /tmp/rsyslog-mysql.sql

- name: Get Loganalyzer
  unarchive:
    src: http://download.adiscon.com/loganalyzer/loganalyzer-4.1.5.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Configure Loganalyzer
  copy:
    src: /tmp/loganalyzer-4.1.5/src/
    dest: /var/www/html/loganalyzer

...