# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :"elk-master" => {
    :box_name => "centos/7",
    :ip_addr => "192.168.11.250",
    :memory => "2048",
    :shell => "prepare_ansible.sh",
    :ansible => "elk-master.yml"
  },
  :"elk-data" => {
    :box_name => "centos/7",
    :ip_addr => "192.168.11.251",
    :memory => "512",
    :shell => "prepare_ansible.sh",
    :ansible => "elk-data.yml"
  },
  :"web-srv" => {
    :box_name => "centos/7",
    :ip_addr => "192.168.11.252",
    :memory => "128",
    :shell => "prepare_ansible.sh",
    :ansible => "web-srv.yml"
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.provider "virtualbox" do |vb|
        vb.name = boxname.to_s
        vb.memory = boxconfig[:memory]
      end
      box.vm.provision "shell", path: "shell/" + boxconfig[:shell]
      box.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "ansible/" + boxconfig[:ansible]
	    end
      box.vm.provision "shell", path: "shell/test_task.sh"
    end
  end
end