---
- name: Install role packages
  import_tasks: install_role_packages.yml

- name: Enable routing
  import_tasks: enable_routing.yml

- name: Create configs from templates
  import_tasks: create_configs.yml
...